import Vue from 'vue';
import Vuex from 'vuex';

import actions from './actions';
import getters from './getters';
import mutations from './mutations';

Vue.use(Vuex);

export const store = new Vuex.Store({
    state: {
        user: {
            id: null,
            developer: false,
        },
        backup: {
            form: null,
        },
        form: {
            serviceEnabled: false,
            service: null,
            option: null,
            optionMin: null,
            madeby: null,
            developer: null,
            addons: null,
            sysAddons: null,
            designSidebar: true,
            designNavbar: false,
            designDashboard: false,
            generalDesigns: [],
            sidebarDesigns: [],
            navbarDesigns: [],
            dashboardDesigns: [],
            footerDesigns: [],
            colors: [],
            design_urls: [],
            title: null,
            description: null,
            projectName: null,
            sector: null,
            inputData: [],
        },
        language: "",
        languages: ["en", "nl"],
        translations: {
            nl: {
                seo: {
                    seo_line: "Bedrijfs Website, Persoonlijke Website, Email, Online Marketing en meer.",
                    seo_lineShort: "Websites, Systemen & Meer",
                    seo_name: "Webzey"
                },
                header: {
                    header_business_website: "Bedrijfs Website",
                    header_personal_website: "Persoonlijke Website",
                    header_app: "Native App",
                    header_online_system: "Online Systeem",
                    header_webshop: "Webshop",
                    header_email: "Persoonlijke Email",
                    header_marketing: "Online Marketing",
                    header_cms: "CMS | Wordpress",
                    header_other: "Anders",
                    header_logo: "Webzey Logo | Bedrijfs Website, Persoonlijke Website, Email, Online Marketing en meer.",
                    header_search: "Zoeken",
                    header_search_placeholder: "Vind product",
                    header_become_partner: "Word een developer",
                    header_sign_up: "Registreer",
                    header_sign_in: "Inloggen",
                    header_dashboard: "Dashboard"
                },
                footer: {
                    footer_contact_questions: "Vragen?",
                    footer_contact_questions_sub: "Neem contact op met onze medewerkers.",
                    footer_contact_information: "Informatie",
                    footer_contact_administration: "Administratie",
                    footer_newsletter: "Meld je aan voor de nieuwsbrief",
                    footer_newsletter_email: "E-mailadres",
                    footer_newsletter_sub: "Ontvang het laatste nieuws.",
                    footer_newsletter_subscribe: "Aanmelden",
                    footer_news: "Laatste nieuws",
                    footer_livechat: "Livechat",
                    footer_status: "Status",
                    footer_about_webzey: "Over webzey",
                    footer_business: "Zakelijk",
                    footer_portfolio: "Portfolio",
                    footer_websites: "Websites",
                    footer_history: "Geschiedenis",
                    footer_about_us: "Over ons",
                    footer_siteMap: "Site Map",
                    footer_account: "Mijn Account",
                    footer_dashboard: "Inzage",
                    footer_system: "Systeem",
                    footer_more_about_business: "Meer over zakelijk",
                    footer_social_media: "Sociale Media",
                    footer_btw: "Alle prijzen zijn excl. 21% BTW",
                    footer_terms: "Algemene voorwaarde",
                    footer_privacy: "Privacy",
                    footer_cookies: "Cookies",
                    footer_copy: "© 2017 - 2020 Webbureau Webzey",
                },
                homePage: {
                    homePage_search_placeholder: "Vind product",
                    homePage_search: "Zoeken",
                    homePage_popular_products: "Populaire producten",
                    homePage_personal_website: "Persoonlijke Website",
                    homePage_business_website: "Bedrijfs Website",
                    homePage_system: "Systemen",
                    homePage_webzey_cms: "The Webzey CMS™",
                    homePage_about_webzey: "Over Webzey",
                    homePage_section_heading_1: "Beste producten volgens onze klanten",
                    homePage_section_heading_2: "Iets over ons zelf",
                    homePage_section_heading_3: "Dingen die wij gebruiken om jouw project de beste te maken",
                    homePage_section_heading_4: "Onze laatste creaties",
                    homePage_about_heading_1: "Wat is Webzey?",
                    homePage_about_paragraph_1: "Webzey is een webbureau die gespecialiseerd is in development. Zo kunt u bij ons terecht voor o.a. uw Software, Website, Systeem, App, Mailservice, Online Marketing & Zoekmachine optimalisatie (SEO). Wanneer u in uw bedrijfsomgeving applicaties in elkaar over wilt laten lopen en gemakkelijk in gebruik wilt hebben zorgen wij hiervoor.",
                    homePage_about_heading_2: "Wat doet Webzey?",
                    homePage_about_paragraph_2: "Webzey zorgt ervoor dat uw idee voor Software omgezet wordt naar een daadwerkelijk product. Hiervoor benaderen wij de beste Developers uit ons team van studenten, of geven u zelf de optie iemand te kiezen waarmee u graag uw project naar een nieuw level wilt tillen.",
                    homePage_about_heading_3: "Wat kan Webzey voor mij betekenen?",
                    homePage_about_paragraph_3: "Webzey kan u helpen om goedkoop uw Software, Website, App of Serivce te ontwikkelen en te hosten. Daarnaast bieden wij extra support voor wanneer u later nog iets extra wilt toevoegen aan uw project. Ook kunt u bij ons gemakkelijk de code van uw project inzien en de status bijhouden via ons interface.",
                    homePage_content_php_node: "Om ervoor te zorgen dat uw website snel alle vraag van uw klanten/bezoekers kan verwerken maken wij gebruik van zowel PHP als NodeJS om ervoor te zorgen dat uw klanten geen enkele problemen ondervinden met de bereikbaarheid van uw website. Uiteindelijk gebruiken we Express en Laravel om ervoor te zorgen dat alle vraag van en na uw website geauthentiseerd wordt en dat uw website in alle tijden beveiligd is.",
                    homePage_button_php_node: "Meer lezen", 
                    homePage_content_html_css: "Om ervoor te zorgen dat uw website/app er goed uitziet maken wij gebruik van HTML5 en CSS3 hiermee hebben wij de mogelijkheid uw website een moderne en geadvanceerde uitstraling te geven. Ook maken wij gebruik van VueJS en Javascript om te zorgen dat uw website zo efficient mogelijk wordt waardoor uw klanten veel sneller een andere pagina op uw website kunenn inladen waardoor de gebruiksvriendelijkheid optimaal wordt.",
                    homePage_content_browser: "Natuurlijk wilt u dat uw website goed gevonden wordt in searchengines zoals Google. Hiervoor heeft u natuurlijk een goede SEO nodig en hierbij kunnen wij u helpen door onze jarenlange ervaring met SEO. ",
                    homePage_item_1_browser: "SSL/TLS",
                    homePage_item_2_browser: "Domeinnaam",
                    homePage_item_3_browser: "Titel",
                    homePage_item_4_browser: "Description",
                    homePage_item_5_browser: "Indeling",
                    homePage_content_react_app: "Om ervoor te zorgen dat klanten/bezoekers u ook altijd bij de hand kunnen hebben doormiddel van uw eigen app. Zorgen wij ervoor dat met React Native uw website ook mogelijk wordt om offline te bezoeken. Ook kunnen we met React Native apps creëren voor uw bedrijf die te downloaden zijn in o.a. de Appstore en PlayStore. ",
                    homePage_rating_content: "wordt beoordeeld door klanten met 5 van 5 sterren.",
                    homePage_product_websites: "Websites",
                    homePage_product_app: "Apps",
                    homePage_product_systems: "Systemen",
                    homePage_product_webshop: "Webshop",
                    homePage_product_1_item_1: "Custom Home Pagina",
                    homePage_product_1_item_2: "Custom extra Pagina",
                    homePage_product_1_item_3: "8 Blokken",
                    homePage_product_1_item_4: "",
                    homePage_product_2_item_1: "Custom Home Pagina",
                    homePage_product_2_item_2: "Custom extra Pagina",
                    homePage_product_2_item_3: "Klein back-end systeem",
                    homePage_product_2_item_4: "",
                    homePage_product_3_item_1: "Custom front-end",
                    homePage_product_3_item_2: "Custom dashboard",
                    homePage_product_3_item_3: "Custom systeem",
                    homePage_product_3_item_4: "API, Databases, etc.",
                    homePage_product_4_item_1: "Custom Design",
                    homePage_product_4_item_2: "",
                    homePage_product_4_item_3: "",
                    homePage_product_4_item_4: "",
                },
                news: {
                    news_button_search: "Zoeken",
                    news_option_privacy: "Privacy",
                    news_option_updates: "Updates",
                    news_option_new_products: "Nieuwe producten",
                    news_option_maintenance: "Onderhoud",
                    news_option_web_servers: "Web Servers",
                    news_mail_servers: "Mail Servers",
                },
                products: {
                   product_placeholder: "checkjouwdomein.nl",
                   product_button_search: "Zoeken",
                   product_title_business: "Bedrijfs Website",
                   product_title_personal: "Persoonlijke Website",
                   product_title_system: "Online Systeem",
                   product_title_webshop: "Webshop",
                   product_title_wordpress: "Wordpress | CMS",
                   product_title_email: "Personal Email",
                   product_title_marketing: "Online Marketing (SEO)",
                   product_title_app: "Mobiele App",
                   product_spec_heading: "Onze ervaringen zorgen voor uw perfecte website",
                   product_spec_sub_heading: "Met onze kennis zorgen wij ervoor dat uw website uitblinkt, Snel reageert, Efficient werkt en een moderne uitstraling geeft.",
                   product_section_heading_1: "Dingen die wij gebruiken om jouw project de beste te maken",
                   product_section_heading_2: "Flexibele serverhosting met veel opties",
                   product_section_sub_heading_2: "Met de webhosting pakketen die wij leveren zorgen wij ervoor dat u op zo'n best mogelijke manier uw website kunt onderhouden.",
                   product_rating_content: "wordt beoordeeld door klanten met 5 van 5 sterren.",
                   product_product_websites: "Websites",
                   product_product_email: "Emails",
                   product_product_systems: "Systemen",
                   product_product_webshop: "Webshop",
                   product_backend: "Om ervoor te zorgen dat uw website snel alle vraag van uw klanten/bezoekers kan verwerken maken wij gebruik van zowel PHP als NodeJS om ervoor te zorgen dat uw klanten geen enkele problemen ondervinden met de bereikbaarheid van uw website. Uiteindelijk gebruiken we Express en Laravel om ervoor te zorgen dat alle vraag van en na uw website geauthentiseerd wordt en dat uw website in alle tijden beveiligd is.",
                   product_frontend: "Om ervoor te zorgen dat uw website/app er goed uitziet maken wij gebruik van HTML5 en CSS3 hiermee hebben wij de mogelijkheid uw website een moderne en geadvanceerde uitstraling te geven. Ook maken wij gebruik van VueJS en Javascript om te zorgen dat uw website zo efficient mogelijk wordt waardoor uw klanten veel sneller een andere pagina op uw website kunenn inladen waardoor de gebruiksvriendelijkheid optimaal wordt.",
                   product_seo: "Natuurlijk wilt u dat uw website goed gevonden wordt in searchengines zoals Google. Hiervoor heeft u natuurlijk een goede SEO nodig en hierbij kunnen wij u helpen door onze jarenlange ervaring met SEO.",
                   product_app: "Om ervoor te zorgen dat klanten/bezoekers u ook altijd bij de hand kunnen hebben doormiddel van uw eigen app. Zorgen wij ervoor dat met React Native uw website ook mogelijk wordt om offline te bezoeken. Ook kunnen we met React Native apps creëren voor uw bedrijf die te downloaden zijn in o.a. de Appstore en PlayStore.",
                   product_personal_heading_1: "Optimale SEO",
                   product_personal_heading_2: "Klantgericht",
                   product_personal_heading_3: "Achterliggend Systeem",
                   procuct_personal_heading_4: "Klantenservice",
                   product_personal_paragraph_1: "Om ervoor te zorgen dat klanten u online kunnen vinden heeft u een goede SEO nodig, waarin o.a. vermeld staat wat u doet d.m.v. afbeeldingen en anekdotes zodat de searchengines gebruikers snel kunnen zien bij een url wat er te verwachten is op de website.",
                   product_personal_paragraph_2: "Om ervoor te zorgen dat uw klanten zo lang mogelijk op de website blijven is een optimale opmaak van belang. Hierin wordt gekeken naar de juiste hoeveelheid tekst en de indeling van uw website.",
                   product_personal_paragraph_3: "Om uiteindelijk de gegevens die uw klanten op uw website invullen te kunnen gebruiken heeft u iets van een achterliggend systeem nodig waar u dit kunt inzien.",
                   product_personal_paragraph_4_1: "Om uw klanten te helpen met eventuele vragen betreft een product of dienst is het van belang dat zij contact met u kunnen opnemen doormiddel van o.a. een livechat. Hiervoor biedt Webzey zijn",
                   product_personal_paragraph_4_2: " aan.",
                   product_business_heading_1: "Blog, Forum, of Biografie",
                   product_business_heading_2: "Optimaal ingericht",
                   product_business_heading_3: "Portfolio",
                   procuct_business_heading_4: "Makkelijk aanpasbaar",
                   product_business_paragraph_1: "Of u nu een Blog, Forum of Biografie wilt hebben wij weten uw website zo te maken dat het geheel naar uw wens is en makkelijk te onderhouden is.",
                   product_business_paragraph_2: "Om te voorkomen dat de bezoekers van uw website overspoeld worden met content zorgen wij ervoor dat alles optimaal ingedeeld is, en uw bezoeker gemakkelijk alles overzichterlijk voor zich heeft.",
                   product_business_paragraph_3: "Om uw bezoekers duidelijk te maken wat u doet is het handig om een protofolio op uw website toe te voegen. Waarmee u laat zien wat u allemaal doet.",
                   product_business_paragraph_4: "Alle sites die wij maken hebben de eis dat ze uiteindelijk voor de eindgebruiker makkelijk aanpasbaar zijn. Dit doen wij door bijvoorbeeld uw teksten te lokaliseren op één centrale locatie.",
                   product_system_heading_1: "Authenticatie",
                   product_system_heading_2: "Rechten",
                   product_system_heading_3: "Intergraties",
                   procuct_system_heading_4: "Data verwerking",
                   product_system_paragraph_1: "Om ervoor te zorgen dat niet iedereen bij uw systeem kan is beveiliging ernorm belangrijk. Hiervoor maken wij dus gebruik van meerdere authenticatie mogelijkheden zoals Password &",
                   product_system_paragraph_2: "Ook is het van belang dat niet iedereen binnen het systeem overal bij kan. Om dit te voorkomen maken wij gebruik van een rechtensysteem. Dit systeem houd per groep bij waar de ingelogde persoon toegang tot heeft.",
                   product_system_paragraph_3: "Het is handig om sommige integraties al in uw website verwerkt te hebben door middel van API's zodat u bijvoorbeeld uw pakket al bij een koeriersdienst aanmeld of dat u een ander programma een opdracht geeft iets uit te voeren.",
                   product_system_paragraph_4: "Om daadwerkelijk iets met data te doen in uw systeem wilt u natuurlijk dat dit door enkele forumules verwerkt wordt en uiteindelijk een overzicht terug geeft.",
                   product_webshop_heading_1: "Optimale SEO",
                   product_webshop_heading_2: "Klantgericht",
                   product_webshop_heading_3: "Betaal mogelijkheden",
                   procuct_webshop_heading_4: "Intergraties",
                   product_webshop_paragraph_1: "Om ervoor te zorgen dat klanten u online kunnen vinden heeft u een goede SEO nodig, waarin o.a. vermeld staat wat u doet d.m.v. afbeeldingen en anekdotes zodat de searchengines gebruikers snel kunnen zien bij een url wat er te verwachten is op de website.",
                   product_webshop_paragraph_2: "Om ervoor te zorgen dat uw klanten zo lang mogelijk op de website blijven is een optimale opmaak van belang. Hierin wordt gekeken naar de juiste hoeveelheid tekst en de indeling van uw website.",
                   product_webshop_paragraph_3: "U wilt natuurlijk dat het uw klanten zo makkelijk mogelijk wordt gemaakt als het gaat om het betalen van een dienst of product. Daarom is het goed als uw klanten kunnen betalen met hun favoriete betaalmethode doormiddel van",
                   product_webshop_paragraph_4: "Het is handig om sommige integraties al in uw website verwerkt te hebben door middel van API's zodat u bijvoorbeeld uw pakket al bij een koeriersdienst aanmeld of dat u een ander programma een opdracht geeft iets uit te voeren.",
                   product_email_heading_1: "Eigen domein",
                   product_email_heading_2: "Lijsten per afdeling",
                   product_email_heading_3: "Autorespond",
                   procuct_email_heading_4: "Anti-Spam",
                   product_email_paragraph_1: "Om goed gevonden te worden is een eigen domeinnaam van belang. Met uw eigen naam@bedrijf.com zorgt u ervoor dat klanten uw onthouden en hierdoor gemakkelijker contact met u kunnen opnemen.",
                   product_email_paragraph_2: "Met uw eigen e-mail kunt u gemakkelijk hele afdelingen binnen uw bedrijf makkelijk een e-mail sturen door de mail te sturen naar lijst-naam@bedrijf.com en het achterliggende systeem zorgt ervoor dat iedereen de mail ontvangt.",
                   product_email_paragraph_3: "Wilt u uw klanten direct een mail terug sturen dan kunt u gebruik maken van autorespond. Autorespond zorgt ervoor dat wanneer klanten een mail sturen naar u dat zij direct een mailtje terug ontvangen met het door u ingestelde bericht.",
                   product_email_paragraph_4: "Om te voorkomen dat uw hele inbox volt zit met spam emails. Wordt er aan de server kant gebruik gemaakt van meerdere anti-spam systemen die ervoor zorgen dat de spam emails uit uw inbox gefilterd worden.",
                   product_marketing_heading_1: "Optimale SEO",
                   product_marketing_heading_2: "Sociale Media",
                   product_marketing_heading_3: "Afbeeldingen",
                   procuct_marketing_heading_4: "Teksten",
                   product_marketing_paragraph_1: "Om te zorgen dat searchengines het maximale uit uw site halen is het belangrijk hem goed in te delen en goed gebruik te maken van 'meta'-tags. Ook is het belangrijk dat u uw sitemap optimaal benut en gebruik maakt van de robot.txt's",
                   product_marketing_paragraph_2: "Om ervoor te zorgen dat uw bedrijf genoeg bezoek trekt is het handig om op meerdere sociale media aanwezig te zijn en support en updates te leveren aan uw klanten. Dit bijvoorbeeld doormiddel van de Direct Message optie te koppelen aan een",
                   product_marketing_paragraph_3: "Om ervoor te zorgen dat u zo hoog mogelijk in de zoekresultaten eindigt is het ook van belang dat uw website zo snel mogelijk inlaat. Hiervoor is het handig om de afbeeldingen in het goede formaat te leveren en de juiste compressie hierop toe te passen.",
                   product_marketing_paragraph_4: "Zoekmachines zoals Google beoordelen websites ook op de teksten en de kwaliteit van deze teksten. Daarom is het belangrijk voor u dat een tekst goed ingedeeld is en dat hij aan de kwaliteitsnormen voldoet van SEO.",
                   product_app_heading_1: "Offline Systeem",
                   product_app_heading_2: "Overal bij de hand",
                   product_app_heading_3: "Appstore & Playstore",
                   procuct_app_heading_4: "Zichtbaarheid",
                   product_app_paragraph_1: "Wilt u uw website offline bezoeken dat kunt u kiezen voor een Native App. Dit geeft u namelijk de mogelijkheid uw website offline in de browser te bekijken en gegevens in te vullen. En wanneer weer verbonden met het internet ook te verzenden.",
                   product_app_paragraph_2: "Doormiddel van een Native App kunt u overal met uw telefoon, laptop of computer de app, of website-versie openen en gebruik maken van de achterliggende systemen en interfaces.",
                   product_app_paragraph_3: "Een Native App is zowel gemaakt voor IOS (Apple) als Android (Google) en kunt u wanneer u wilt openbaar maken in de Google Playstore of de Apple Appstore.",
                   product_app_paragraph_4: "Doordat uw klanten uw App geinstaleerd hebben op hun devices komen ze de app meerdere malen per dag tegen zonder dat ze er zelf erg op letten. Hierdoor zullen ze uw bedrijf weer eerder kiezen boven andere bedrijven.",
                }
            }
        }
    },
    getters,
    mutations,
    actions,
    modules: {

    }
});